/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PharmacyId = IDL.Nat;
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StatutPharmacie = IDL.Variant({
  'validee' : IDL.Null,
  'enAttente' : IDL.Null,
  'suspendue' : IDL.Null,
});
export const Pharmacie = IDL.Record({
  'id' : PharmacyId,
  'ownerId' : IDL.Opt(IDL.Principal),
  'nombreVues' : IDL.Nat,
  'commune' : IDL.Text,
  'nomPharmacie' : IDL.Text,
  'statutOuvert' : IDL.Bool,
  'adresse' : IDL.Text,
  'telephone' : IDL.Text,
  'statutPharmacie' : StatutPharmacie,
  'horaires' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'pharmacy' : IDL.Null,
});
export const StatutCompte = IDL.Variant({
  'actif' : IDL.Null,
  'suspendu' : IDL.Null,
  'enAttente' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'nom' : IDL.Text,
  'role' : UserRole,
  'statutCompte' : StatutCompte,
  'email' : IDL.Text,
});
export const Utilisateur = IDL.Record({
  'id' : IDL.Principal,
  'nom' : IDL.Text,
  'role' : UserRole,
  'statutCompte' : StatutCompte,
  'email' : IDL.Text,
  'motDePasseHash' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'ajoutParAdmin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [PharmacyId],
      [],
    ),
  'ajoutParPharmacie' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [PharmacyId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAdminPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
  'getAllPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getMesPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
  'getMesPharmaciesVues' : IDL.Func([PharmacyId], [IDL.Nat], ['query']),
  'getPharmacyById' : IDL.Func([PharmacyId], [IDL.Opt(Pharmacie)], []),
  'getTousLesUtilisateurs' : IDL.Func([], [IDL.Vec(Utilisateur)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUtilisateur' : IDL.Func([], [Utilisateur], ['query']),
  'getUtilisateursPharmacies' : IDL.Func([], [IDL.Vec(Utilisateur)], ['query']),
  'initAdmin' : IDL.Func([], [IDL.Text], []),
  'inscriptionUtilisateur' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'modifierStatutUtilisateur' : IDL.Func([IDL.Principal, StatutCompte], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'supprimerPharmacie' : IDL.Func([PharmacyId], [], []),
  'updatePharmacieProprietaire' : IDL.Func(
      [PharmacyId, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'validatePharmacie' : IDL.Func([PharmacyId, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PharmacyId = IDL.Nat;
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StatutPharmacie = IDL.Variant({
    'validee' : IDL.Null,
    'enAttente' : IDL.Null,
    'suspendue' : IDL.Null,
  });
  const Pharmacie = IDL.Record({
    'id' : PharmacyId,
    'ownerId' : IDL.Opt(IDL.Principal),
    'nombreVues' : IDL.Nat,
    'commune' : IDL.Text,
    'nomPharmacie' : IDL.Text,
    'statutOuvert' : IDL.Bool,
    'adresse' : IDL.Text,
    'telephone' : IDL.Text,
    'statutPharmacie' : StatutPharmacie,
    'horaires' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'pharmacy' : IDL.Null,
  });
  const StatutCompte = IDL.Variant({
    'actif' : IDL.Null,
    'suspendu' : IDL.Null,
    'enAttente' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'nom' : IDL.Text,
    'role' : UserRole,
    'statutCompte' : StatutCompte,
    'email' : IDL.Text,
  });
  const Utilisateur = IDL.Record({
    'id' : IDL.Principal,
    'nom' : IDL.Text,
    'role' : UserRole,
    'statutCompte' : StatutCompte,
    'email' : IDL.Text,
    'motDePasseHash' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'ajoutParAdmin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
        [PharmacyId],
        [],
      ),
    'ajoutParPharmacie' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [PharmacyId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAdminPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
    'getAllPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getMesPharmacies' : IDL.Func([], [IDL.Vec(Pharmacie)], ['query']),
    'getMesPharmaciesVues' : IDL.Func([PharmacyId], [IDL.Nat], ['query']),
    'getPharmacyById' : IDL.Func([PharmacyId], [IDL.Opt(Pharmacie)], []),
    'getTousLesUtilisateurs' : IDL.Func([], [IDL.Vec(Utilisateur)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUtilisateur' : IDL.Func([], [Utilisateur], ['query']),
    'getUtilisateursPharmacies' : IDL.Func(
        [],
        [IDL.Vec(Utilisateur)],
        ['query'],
      ),
    'initAdmin' : IDL.Func([], [IDL.Text], []),
    'inscriptionUtilisateur' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'modifierStatutUtilisateur' : IDL.Func(
        [IDL.Principal, StatutCompte],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'supprimerPharmacie' : IDL.Func([PharmacyId], [], []),
    'updatePharmacieProprietaire' : IDL.Func(
        [PharmacyId, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'validatePharmacie' : IDL.Func([PharmacyId, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };