/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Pharmacie {
  'id' : PharmacyId,
  'ownerId' : [] | [Principal],
  'nombreVues' : bigint,
  'commune' : string,
  'nomPharmacie' : string,
  'statutOuvert' : boolean,
  'adresse' : string,
  'telephone' : string,
  'horaires' : string,
  'valideParAdmin' : boolean,
}
export type PharmacyId = bigint;
export type StatutCompte = { 'actif' : null } |
  { 'suspendu' : null } |
  { 'enAttente' : null };
export interface UserProfile {
  'nom' : string,
  'role' : UserRole,
  'statutCompte' : StatutCompte,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'pharmacy' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Utilisateur {
  'id' : Principal,
  'nom' : string,
  'role' : UserRole,
  'statutCompte' : StatutCompte,
  'email' : string,
  'motDePasseHash' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'ajoutParAdmin' : ActorMethod<
    [string, string, string, string, string, boolean, boolean],
    PharmacyId
  >,
  'ajoutParPharmacie' : ActorMethod<
    [string, string, string, string, string],
    PharmacyId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getAdminPharmacies' : ActorMethod<[], Array<Pharmacie>>,
  'getAllPharmacies' : ActorMethod<[], Array<Pharmacie>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getMesPharmacies' : ActorMethod<[], Array<Pharmacie>>,
  'getMesPharmaciesVues' : ActorMethod<[PharmacyId], bigint>,
  'getPharmacyById' : ActorMethod<[PharmacyId], [] | [Pharmacie]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUtilisateur' : ActorMethod<[], Utilisateur>,
  'getUtilisateursPharmacies' : ActorMethod<[], Array<Utilisateur>>,
  'initAdmin' : ActorMethod<[], string>,
  'inscriptionUtilisateur' : ActorMethod<
    [string, string, string, UserRole],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'modifierStatutUtilisateur' : ActorMethod<
    [Principal, StatutCompte],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePharmacieProprietaire' : ActorMethod<
    [PharmacyId, string, string, string, boolean],
    undefined
  >,
  'validatePharmacie' : ActorMethod<[PharmacyId, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];