/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Utilisateur {
    id: Principal;
    nom: string;
    role: UserRole;
    statutCompte: StatutCompte;
    email: string;
    motDePasseHash: string;
}
export type PharmacyId = bigint;
export interface Pharmacie {
    id: PharmacyId;
    ownerId?: Principal;
    nombreVues: bigint;
    commune: string;
    nomPharmacie: string;
    statutOuvert: boolean;
    adresse: string;
    telephone: string;
    statutPharmacie: StatutPharmacie;
    horaires: string;
}
export interface UserProfile {
    nom: string;
    role: UserRole;
    statutCompte: StatutCompte;
    email: string;
}
export enum StatutCompte {
    actif = "actif",
    suspendu = "suspendu",
    enAttente = "enAttente"
}
export enum StatutPharmacie {
    validee = "validee",
    enAttente = "enAttente",
    suspendue = "suspendue"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    pharmacy = "pharmacy"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    ajoutParAdmin(nomPharmacie: string, commune: string, adresse: string, telephone: string, horaires: string, statutOuvert: boolean, valideParAdmin: boolean): Promise<PharmacyId>;
    ajoutParPharmacie(nomPharmacie: string, commune: string, adresse: string, telephone: string, horaires: string): Promise<PharmacyId>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    getAdminPharmacies(): Promise<Array<Pharmacie>>;
    getAllPharmacies(): Promise<Array<Pharmacie>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getMesPharmacies(): Promise<Array<Pharmacie>>;
    getMesPharmaciesVues(id: PharmacyId): Promise<bigint>;
    getPharmacyById(id: PharmacyId): Promise<Pharmacie | null>;
    getTousLesUtilisateurs(): Promise<Array<Utilisateur>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUtilisateur(): Promise<Utilisateur>;
    getUtilisateursPharmacies(): Promise<Array<Utilisateur>>;
    initAdmin(): Promise<string>;
    inscriptionUtilisateur(nom: string, email: string, motDePasse: string, role: UserRole): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    modifierStatutUtilisateur(userId: Principal, statutCompte: StatutCompte): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    supprimerPharmacie(pharmacyId: PharmacyId): Promise<void>;
    updatePharmacieProprietaire(id: PharmacyId, horaires: string, telephone: string, adresse: string, statutOuvert: boolean): Promise<void>;
    validatePharmacie(pharmacyId: PharmacyId, validation: boolean): Promise<void>;
}
import type { Pharmacie as _Pharmacie, PharmacyId as _PharmacyId, StatutCompte as _StatutCompte, StatutPharmacie as _StatutPharmacie, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, Utilisateur as _Utilisateur } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async ajoutParAdmin(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: boolean): Promise<PharmacyId> {
        if (this.processError) {
            try {
                const result = await this.actor.ajoutParAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ajoutParAdmin(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async ajoutParPharmacie(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<PharmacyId> {
        if (this.processError) {
            try {
                const result = await this.actor.ajoutParPharmacie(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ajoutParPharmacie(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAdminPharmacies(): Promise<Array<Pharmacie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPharmacies();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPharmacies();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPharmacies(): Promise<Array<Pharmacie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPharmacies();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPharmacies();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMesPharmacies(): Promise<Array<Pharmacie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMesPharmacies();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMesPharmacies();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMesPharmaciesVues(arg0: PharmacyId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMesPharmaciesVues(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMesPharmaciesVues(arg0);
            return result;
        }
    }
    async getPharmacyById(arg0: PharmacyId): Promise<Pharmacie | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacyById(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacyById(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTousLesUtilisateurs(): Promise<Array<Utilisateur>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTousLesUtilisateurs();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTousLesUtilisateurs();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUtilisateur(): Promise<Utilisateur> {
        if (this.processError) {
            try {
                const result = await this.actor.getUtilisateur();
                return from_candid_Utilisateur_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUtilisateur();
            return from_candid_Utilisateur_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUtilisateursPharmacies(): Promise<Array<Utilisateur>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUtilisateursPharmacies();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUtilisateursPharmacies();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async initAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin();
            return result;
        }
    }
    async inscriptionUtilisateur(arg0: string, arg1: string, arg2: string, arg3: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.inscriptionUtilisateur(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.inscriptionUtilisateur(arg0, arg1, arg2, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async modifierStatutUtilisateur(arg0: Principal, arg1: StatutCompte): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.modifierStatutUtilisateur(arg0, to_candid_StatutCompte_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.modifierStatutUtilisateur(arg0, to_candid_StatutCompte_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async supprimerPharmacie(arg0: PharmacyId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.supprimerPharmacie(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.supprimerPharmacie(arg0);
            return result;
        }
    }
    async updatePharmacieProprietaire(arg0: PharmacyId, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePharmacieProprietaire(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePharmacieProprietaire(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async validatePharmacie(arg0: PharmacyId, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePharmacie(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePharmacie(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Pharmacie_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Pharmacie): Pharmacie {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_StatutCompte_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatutCompte): StatutCompte {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StatutPharmacie_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StatutPharmacie): StatutPharmacie {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Utilisateur_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Utilisateur): Utilisateur {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Pharmacie]): Pharmacie | null {
    return value.length === 0 ? null : from_candid_Pharmacie_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: string;
    role: _UserRole;
    statutCompte: _StatutCompte;
    email: string;
}): {
    nom: string;
    role: UserRole;
    statutCompte: StatutCompte;
    email: string;
} {
    return {
        nom: value.nom,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        statutCompte: from_candid_StatutCompte_n14(_uploadFile, _downloadFile, value.statutCompte),
        email: value.email
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    nom: string;
    role: _UserRole;
    statutCompte: _StatutCompte;
    email: string;
    motDePasseHash: string;
}): {
    id: Principal;
    nom: string;
    role: UserRole;
    statutCompte: StatutCompte;
    email: string;
    motDePasseHash: string;
} {
    return {
        id: value.id,
        nom: value.nom,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        statutCompte: from_candid_StatutCompte_n14(_uploadFile, _downloadFile, value.statutCompte),
        email: value.email,
        motDePasseHash: value.motDePasseHash
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PharmacyId;
    ownerId: [] | [Principal];
    nombreVues: bigint;
    commune: string;
    nomPharmacie: string;
    statutOuvert: boolean;
    adresse: string;
    telephone: string;
    statutPharmacie: _StatutPharmacie;
    horaires: string;
}): {
    id: PharmacyId;
    ownerId?: Principal;
    nombreVues: bigint;
    commune: string;
    nomPharmacie: string;
    statutOuvert: boolean;
    adresse: string;
    telephone: string;
    statutPharmacie: StatutPharmacie;
    horaires: string;
} {
    return {
        id: value.id,
        ownerId: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.ownerId)),
        nombreVues: value.nombreVues,
        commune: value.commune,
        nomPharmacie: value.nomPharmacie,
        statutOuvert: value.statutOuvert,
        adresse: value.adresse,
        telephone: value.telephone,
        statutPharmacie: from_candid_StatutPharmacie_n7(_uploadFile, _downloadFile, value.statutPharmacie),
        horaires: value.horaires
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    pharmacy: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "pharmacy" in value ? UserRole.pharmacy : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    actif: null;
} | {
    suspendu: null;
} | {
    enAttente: null;
}): StatutCompte {
    return "actif" in value ? StatutCompte.actif : "suspendu" in value ? StatutCompte.suspendu : "enAttente" in value ? StatutCompte.enAttente : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    validee: null;
} | {
    enAttente: null;
} | {
    suspendue: null;
}): StatutPharmacie {
    return "validee" in value ? StatutPharmacie.validee : "enAttente" in value ? StatutPharmacie.enAttente : "suspendue" in value ? StatutPharmacie.suspendue : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Utilisateur>): Array<Utilisateur> {
    return value.map((x)=>from_candid_Utilisateur_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Pharmacie>): Array<Pharmacie> {
    return value.map((x)=>from_candid_Pharmacie_n4(_uploadFile, _downloadFile, x));
}
function to_candid_StatutCompte_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatutCompte): _StatutCompte {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: string;
    role: UserRole;
    statutCompte: StatutCompte;
    email: string;
}): {
    nom: string;
    role: _UserRole;
    statutCompte: _StatutCompte;
    email: string;
} {
    return {
        nom: value.nom,
        role: to_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        statutCompte: to_candid_StatutCompte_n24(_uploadFile, _downloadFile, value.statutCompte),
        email: value.email
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    pharmacy: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.pharmacy ? {
        pharmacy: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StatutCompte): {
    actif: null;
} | {
    suspendu: null;
} | {
    enAttente: null;
} {
    return value == StatutCompte.actif ? {
        actif: null
    } : value == StatutCompte.suspendu ? {
        suspendu: null
    } : value == StatutCompte.enAttente ? {
        enAttente: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
